[phases.setup]
nixPkgs = ["python39", "gcc"]

[phases.install]
cmds = [
    "pip install --upgrade pip",
    "pip install -r requirements.txt"
]

[phases.build]
cmds = [
    "python scripts/init_db.py"
]

[start]
cmd = "python main.py"
