services:
  - type: web
    name: webchat-backend
    env: docker
    plan: starter
    dockerfilePath: ./Dockerfile
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: ENVIRONMENT
        value: production
