services:
  - type: web
    name: webchat-nodejs
    env: node
    plan: starter
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_VERSION
        value: 18.17.0
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 8000
      - key: DATABASE_URL
        value: sqlite:///./app.db
      - key: JWT_SECRET_KEY
        generateValue: true
      - key: JWT_ALGORITHM
        value: HS256
      - key: JWT_ACCESS_TOKEN_EXPIRE_MINUTES
        value: 60
      - key: SECRET_KEY
        generateValue: true
      - key: BCRYPT_ROUNDS
        value: 12
      - key: ENABLE_VOICE
        value: false
      - key: ENABLE_CAPTCHA
        value: false
      - key: ENABLE_DARK_MODE
        value: true
      - key: RATE_LIMIT_SEARCH
        value: 5
      - key: RATE_LIMIT_UPLOAD
        value: 10
      - key: RATE_LIMIT_LOGIN
        value: 3
      - key: MAX_FILE_SIZE
        value: 5242880
      - key: UPLOAD_DIR
        value: ./uploads
      - key: LOG_LEVEL
        value: INFO
      - key: LOG_FILE
        value: ./logs/app.log
      - key: ADMIN_USERNAME
        value: admin
      - key: ADMIN_PASSWORD
        generateValue: true
